codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "65...90"

  status:
    project:
      default:
        threshold: 0.5 # Allow the coverage to drop by threshold %, and posting a success status.
    patch:
      default:
        target: 0% # trial operation
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - ".git"
  - "*.yml"
  - "*.md"
  # ignore test files
  - "test*.c"
  # ignore sd-daemon.* since it's vendored as external lib
  - "sd-daemon.*"
  # ignore folders and all its contents
  - "adm/.*"
  - "ct/.*"
  - "doc/.*"
  - "pkg/.*"
