codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project: no
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  # ignore files using wildcards
  - "test*.c"
  # ignore folders and all its contents
  - "ct/.*"
  - "adm/.*"
  - "pkg/.*"
