#!/bin/sh

clean=0

while test $# -gt 0; do
  if test "$1" = "--clean"; then
    clean=1
  fi
  shift
done

if test "$clean" = "1"; then
	echo "Cleaning autogenerated files"
	${MAKE:-make} -s -f build.mk clean
else 
	${MAKE:-make} -s -f build.mk
fi

